<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit99b67eeb4786ea7b52839f8961684388::getLoader();
